version: '3'

secrets:
  LLDAP_JWT_SECRET_FILE:
    file: ${CONFIG_PATH}/lldap/secrets/LLDAP_JWT_SECRET_FILE
  LLDAP_LDAP_USER_PASS_FILE:
    file: ${CONFIG_PATH}/lldap/secrets/LLDAP_LDAP_USER_PASS_FILE

services:
  ## Docker Hub: https://hub.docker.com/r/lldap/lldap
  ## Docs: https://github.com/lldap/lldap/blob/main/README.md
  lldap:
    image: lldap/lldap:${LLDAP_VERSION:-stable}
    container_name: lldap
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 3890
    secrets: [ LLDAP_JWT_SECRET_FILE, LLDAP_LDAP_USER_PASS_FILE ]
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
      LLDAP_JWT_SECRET_FILE: /run/secrets/LLDAP_JWT_SECRET_FILE
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/LLDAP_LDAP_USER_PASS_FILE
      LLDAP_LDAP_BASE_DN: dc=${SLD},dc=${TLD}
    volumes:
      - "${CONFIG_PATH}/lldap/data:/data:rw"
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap-rtr.entrypoints=websecure
      - traefik.http.routers.lldap-rtr.rule=Host(`lldap.${DOMAIN}`)
      - traefik.http.routers.lldap-rtr.service=lldap-svc
      - traefik.http.services.lldap-svc.loadbalancer.server.port=17170
      # - traefik.http.routers.lldap-rtr.middlewares=authelia@docker

networks:
  proxy:
    external: true
