version: '3'

secrets:
  LLDAP_JWT_SECRET_FILE:
    file: ${CONFIG}/secrets/lldap/LLDAP_JWT_SECRET_FILE
  LLDAP_LDAP_USER_PASS_FILE:
    file: ${CONFIG}/secrets/lldap/LLDAP_LDAP_USER_PASS_FILE
  LLDAP_SMTP_OPTIONS__PASSWORD_FILE:
    file: ${CONFIG}/secrets/lldap/LLDAP_SMTP_OPTIONS__PASSWORD_FILE

services:
  ## LLDAP - Light LDAP implementation for authentication
  ## Docker Hub: https://hub.docker.com/r/lldap/lldap
  ## Docs: https://github.com/lldap/lldap/blob/main/README.md
  lldap:
    image: lldap/lldap:${LLDAP_VERSION:-stable}
    container_name: lldap
    restart: unless-stopped
    networks:
      - proxy
      - smtp
    expose:
      - 3890
    secrets:
      [
        LLDAP_JWT_SECRET_FILE,
        LLDAP_LDAP_USER_PASS_FILE,
        LLDAP_SMTP_OPTIONS__PASSWORD_FILE
      ]
    environment:
      TZ: ${TZ}
      UID: ${UUID}
      GID: ${GGID}
      LLDAP_VERBOSE: false
      LLDAP_HTTP_URL: https://lldap.${DOMAIN}
      LLDAP_JWT_SECRET_FILE: /run/secrets/LLDAP_JWT_SECRET_FILE
      LLDAP_LDAP_USER_PASS_FILE: /run/secrets/LLDAP_LDAP_USER_PASS_FILE
      LLDAP_LDAP_BASE_DN: dc=${SLD},dc=${TLD}
      LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: true
      LLDAP_SMTP_OPTIONS__SERVER: ${SMTP_HOST}
      LLDAP_SMTP_OPTIONS__PORT: ${SMTP_PORT}
      LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: NONE
      LLDAP_SMTP_OPTIONS__USER: ${SMTP_USERNAME}
      LLDAP_SMTP_OPTIONS__PASSWORD_FILE: /run/secrets/LLDAP_SMTP_OPTIONS__PASSWORD_FILE
      LLDAP_SMTP_OPTIONS__FROM: ${SMTP_FROM}
    volumes:
      - "${SPRING_VOLUME}/lldap/data:/data:rw"
    labels:
      - 'traefik.enable=true'
      # web
      - 'traefik.http.routers.lldap-rtr.entrypoints=websecure'
      - 'traefik.http.routers.lldap-rtr.rule=Host(`lldap.${DOMAIN}`)'
      - 'traefik.http.routers.lldap-rtr.service=lldap-svc'
      - 'traefik.http.services.lldap-svc.loadbalancer.server.port=17170'

networks:
  proxy:
    external: true
  smtp:
    external: true
