version: '3'

services:
  ## Docker Hub: https://hub.docker.com/r/lldap/lldap
  ## Docs: https://github.com/lldap/lldap
  lldap:
    image: lldap/lldap:${LLDAP_VERSION:-stable}
    container_name: lldap
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "3890:3890" # LDAP
      # - "6360:6360" # LDAPS (LDAP Over SSL)
      # - "17170:17170" # Web front-end
    environment:
      - UID=${UID}
      - GID=${GID}
      - TZ=${TZ}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_LDAP_BASE_DN=dc=${SLD},dc=${TLD}
      # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
    volumes:
      - "${CONFIG_PATH}/lldap/data:/data:rw"
    labels:
      - traefik.enable=true
      - traefik.http.routers.lldap-rtr.entrypoints=websecure
      - traefik.http.routers.lldap-rtr.rule=Host(`lldap.${DOMAIN}`)
      - traefik.http.routers.lldap-rtr.service=lldap-svc
      - traefik.http.services.lldap-svc.loadbalancer.server.port=17170
      # - traefik.http.routers.lldap-rtr.middlewares=authelia@docker

networks:
  proxy:
    name: proxy
