version: '3'

secrets:
  AUTHELIA_JWT_SECRET_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_JWT_SECRET_FILE
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
  AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
  AUTHELIA_SESSION_SECRET_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_SESSION_SECRET_FILE
  AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
  AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE:
    file: ${CONFIG}/secrets/authelia/AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE

services:
  ## Authelia - Authentication and authorization server
  ## Docker Hub: https://hub.docker.com/r/authelia/authelia
  ## Docs: https://www.authelia.com/
  authelia:
    image: authelia/authelia:${AUTHELIA_VERSION:-latest}
    container_name: authelia
    restart: unless-stopped
    networks:
      - proxy
      - smtp
    expose:
      - 9091
    secrets:
      [
        AUTHELIA_JWT_SECRET_FILE,
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE,
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE,
        AUTHELIA_SESSION_SECRET_FILE,
        AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE,
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE,
        AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
      ]
    environment:
      TZ: ${TZ}
      GID: ${GGID}
      UID: ${UUID}
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/AUTHELIA_JWT_SECRET_FILE
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /run/secrets/AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/AUTHELIA_SESSION_SECRET_FILE
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    volumes:
      - "${SPRING_VOLUME}/authelia/config:/config:rw"
    labels:
      - 'traefik.enable=true'
      # web
      - 'traefik.http.routers.authelia-rtr.rule=Host(`auth.${DOMAIN}`)'
      - 'traefik.http.routers.authelia-rtr.entrypoints=websecure'
      # middleware
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

networks:
  proxy:
    external: true
  smtp:
    external: true
