version: '3'

services:
  ## Docker Hub: https://hub.docker.com/r/authelia/authelia
  ## Docs: https://www.authelia.com/
  authelia:
    image: authelia/authelia:${AUTHELIA_VERSION:-latest}
    container_name: authelia
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 9091
    environment:
      TZ: ${TZ}
      GID: ${GID}
      UID: ${UID}
      # AUTHELIA_JWT_SECRET_FILE: ${AUTHELIA_JWT_SECRET_FILE}
      # AUTHELIA_SESSION_SECRET_FILE: ${AUTHELIA_SESSION_SECRET_FILE}
      # AUTHELIA_SESSION_REDIS_PASSWORD_FILE: ${AUTHELIA_SESSION_REDIS_PASSWORD_FILE}
    volumes:
      - "${CONFIG_PATH}/authelia/config:/config:rw"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia-rtr.rule=Host(`auth.${DOMAIN}`)'
      - 'traefik.http.routers.authelia-rtr.entrypoints=websecure'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

networks:
  proxy:
    external: true
