services:
  # Traefik - Reverse Proxy
  # Docker Hub: https://hub.docker.com/_/traefik
  # Docs: https://doc.traefik.io/traefik/
  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - proxy
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TZ: ${TZ:-Europe/London}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLPATH}/traefik/certificates:/letsencrypt:rw
      - ${VOLPATH}/traefik/config:/etc/traefik:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik1.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.traefik-rtr.service=api@internal

  ## AdGuard Home - Network-wide ads & trackers blocking DNS server
  ## Docker Hub: https://hub.docker.com/r/adguard/adguardhome
  ## Docs: https://adguard-dns.io/kb/adguard-home/overview/
  adguard:
    image: adguard/adguardhome:${ADGUARD_VERSION:-latest}
    container_name: adguard
    restart: unless-stopped
    ports:
      - 53:53/udp         # Plain DNS port
      # - 3000:3000/tcp     # Admin panel port for initial installation
    networks:
      - proxy
    volumes:
      - ${VOLPATH}/adguard/data:/opt/adguardhome/work
      - ${VOLPATH}/adguard/config:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard-rtr.entrypoints=websecure
      - traefik.http.routers.adguard-rtr.rule=Host(`adguard.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.adguard-rtr.service=adguard-svc
      - traefik.http.services.adguard-svc.loadbalancer.server.port=80

  ## Nginx - Web Server
  ## Docker Hub: https://hub.docker.com/_/nginx
  ## Docs: https://nginx.org/en/docs/
  status:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: status
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${VOLPATH}/status/html:/usr/share/nginx/html:rw
      - ${VOLPATH}/status/config:/etc/nginx/conf.d:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.status-rtr.entrypoints=websecure
      - traefik.http.routers.status-rtr.rule=Host(`status.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.status-rtr.service=status-svc
      - traefik.http.services.status-svc.loadbalancer.server.port=80

networks:
  proxy:
    name: proxy
