services:

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    container_name: traefik
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - proxy
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      TZ: ${TZ:-Europe/London}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOL_PATH}/traefik/certificates:/letsencrypt:rw
      - ${VOL_PATH}/traefik/config:/etc/traefik:ro
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.traefik-rtr.entrypoints=websecure
    #   - traefik.http.routers.traefik-rtr.rule=Host(`traefik2.${DOMAIN:-docker.localhost}`)
    #   - traefik.http.routers.traefik-rtr.service=api@internal

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy
    environment:
      JELLYFIN_PublishedServerUrl: https://media.${DOMAIN:-docker.localhost}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TZ: ${TZ:-Europe/London}
    volumes:
      - ${VOL_PATH}/jellyfin/config:/config:rw
      - ${VOL_PATH}/jellyfin/cache:/cache:rw
      - ${MEDIA_PATH}:/media:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin-rtr.entrypoints=websecure
      - traefik.http.routers.jellyfin-rtr.rule=Host(`media.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.jellyfin-rtr.service=jellyfin-svc
      - traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096

  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - ${VOL_PATH}/qbittorrent/config:/config:rw
      - ${DOWNLOAD_PATH}/qbittorrent:/downloads:rw
      - ${DOWNLOAD_PATH}/qbittorrent/watch:/watch:rw
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-rtr.entrypoints=web
      - traefik.http.routers.qbittorrent-rtr.rule=Host(`torrent.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc
      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
    restart: unless-stopped

  whoami:
    container_name: whoami
    hostname: whoami
    image: traefik/whoami:${WHOAMI_VERSION:-latest}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN:-docker.localhost}`)
      - traefik.http.routers.whoami.service=whoami
      - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  proxy:
    name: proxy
