services:
  nocodb:
    image: nocodb/nocodb:${NOCODB_VERSION:-latest}
    container_name: nocodb
    # ports:
    #   - 8080:8080
    networks:
      - proxy
      - productivity
    depends_on:
      - productivity-db
        # condition: service_healthy
    environment:
      - NC_DB=pg://productivity-db:5432?u=nocodb&p=${NC_DB_PASS}&d=nocodb
      - NC_PUBLIC_URL=https://nocodb.${DOMAIN}
      - NC_DISABLE_TELE=true
      - NC_AUTH_JWT_SECRET=${NC_AUTH_JWT_SECRET}
    volumes:
      - ${VOLUMES_PATH}/productivity/nocodb:/usr/app/data:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.nocodb-rtr.entrypoints=websecure
      - traefik.http.routers.nocodb-rtr.rule=Host(`nocodb.${DOMAIN}`)
      - traefik.http.routers.nocodb-rtr.service=nocodb-svc
      - traefik.http.services.nocodb-svc.loadbalancer.server.port=8080
    restart: unless-stopped

  productivity-db:
    image: postgres:15
    container_name: productivity-db
    networks:
      - productivity
    volumes:
      - ${VOLUMES_PATH}/productivity/postgres:/var/lib/postgresql/data:rw
    environment:
      # - POSTGRES_DB=${NC_DB_NAME}
      # - POSTGRES_USER=${NC_DB_USER}
      - POSTGRES_PASSWORD=${NC_DB_PASS}
    # healthcheck:
    #   test: pg_isready -U ${NC_DB_USER} -d ${NC_DB_NAME}
    #   interval: 10s
    #   timeout: 2s
    #   retries: 10
    restart: unless-stopped

networks:
  productivity:
    name: productivity
  proxy:
    external: true
