version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 9091
    environment:
      - TZ=${TZ}
    volumes:
      - "${CONFIG_PATH}/authelia/config:/config:ro"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia-rtr.rule=Host(`auth.${DOMAIN}`)'
      - 'traefik.http.routers.authelia-rtr.entrypoints=websecure'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${DOMAIN}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    healthcheck:
      disable: true

networks:
  proxy:
    external: true
