version: "3.7"

services:
  ## Gitea - Self-hosted Git service
  ## Docker Hub: https://hub.docker.com/r/gitea/gitea/
  ## Docs: https://docs.gitea.com/
  gitea:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - "3000:3000"
    #   - "666:22"
    volumes:
      - "${CONFIG}/gitea/data:/data"
    environment:
      USER_UID: ${UUID}
      USER_GID: ${GGID}
      SSH_PORT: 666
      SSH_LISTEN_PORT: 22
      ROOT_URL: "https://gitea.${DOMAIN}"
      DOMAIN: "gitea.${DOMAIN}"
      SSH_DOMAIN: "gitea.${DOMAIN}"
      # GITEA__mailer__ENABLED: true
      # GITEA__mailer__PROTOCOL: "smtp+starttls"
      # GITEA__mailer__FROM: "${SMTP_FROM}"
      # GITEA__mailer__SMTP_ADDR: "${SMTP_HOST}"
      # GITEA__mailer__SMTP_PORT: ${SMTP_PORT}
      # GITEA__mailer__USER: "${SMTP_USERNAME}"
      # GITEA__mailer__PASSWD: "${SMTP_PASSWORD}"
      # GITEA__mailer__FORCE_TRUST_SERVER_CERT: true

      GITEA__service__DISABLE_REGISTRATION: false
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true

      # GITEA__service__REGISTER_EMAIL_CONFIRM: true
      # GITEA__service__ENABLE_NOTIFY_MAIL: true
      # GITEA__service__REQUIRE_SIGNIN_VIEW: true

      GITEA__openid__ENABLE_OPENID_SIGNUP: true
      GITEA__openid__ENABLE_OPENID_SIGNIN: false
      GITEA__openid__WHITELISTED_URIS: auth.${DOMAIN}
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.giteaWeb-rtr.entrypoints=websecure
      - traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN}`)
      - traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc
      - traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000
      # - traefik.http.routers.giteaWeb-rtr.middlewares=authelia@file
      # ssh
      - traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh
      - traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc
      - traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22

networks:
  proxy:
    external: true
    name: proxy
