version: '3'

secrets:
  GITEA_DB_PASS:
    file: ${CONFIG}/secrets/gitea/GITEA_DB_PASS

services:
  ## Gitea - Self-hosted Git service
  ## Docker Hub: https://hub.docker.com/r/gitea/gitea/
  ## Docs: https://docs.gitea.com/
  gitea:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea
    restart: unless-stopped
    networks:
      - proxy
      - smtp
      - gitea
    # ports:
    #   - "3000:3000"
    #   - "666:22"
    volumes:
      - "${SPRING_VOLUME}/gitea/data:/data"
    environment:
      USER_UID: ${UUID}
      USER_GID: ${GGID}
      SSH_PORT: 666
      SSH_LISTEN_PORT: 22
      ROOT_URL: "https://gitea.${DOMAIN}"
      DOMAIN: "gitea.${DOMAIN}"
      SSH_DOMAIN: "gitea.${DOMAIN}"
      # SMTP
      GITEA__mailer__ENABLED: true
      GITEA__mailer__PROTOCOL: "smtp+starttls"
      GITEA__mailer__FROM: "${SMTP_FROM}"
      GITEA__mailer__SMTP_ADDR: "${SMTP_HOST}"
      GITEA__mailer__SMTP_PORT: ${SMTP_PORT}
      GITEA__mailer__USER: "${SMTP_USERNAME}"
      GITEA__mailer__PASSWD: "${SMTP_PASSWORD}"
      GITEA__mailer__FORCE_TRUST_SERVER_CERT: true
      # OpenID
      GITEA__service__DISABLE_REGISTRATION: false
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      GITEA__openid__ENABLE_OPENID_SIGNUP: true
      GITEA__openid__ENABLE_OPENID_SIGNIN: false
      GITEA__openid__WHITELISTED_URIS: "auth.${DOMAIN}"
      #
      # GITEA__service__REGISTER_EMAIL_CONFIRM: true
      # GITEA__service__ENABLE_NOTIFY_MAIL: true
      # GITEA__service__REQUIRE_SIGNIN_VIEW: true
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.giteaWeb-rtr.entrypoints=websecure
      - traefik.http.routers.giteaWeb-rtr.rule=Host(`gitea.${DOMAIN}`)
      - traefik.http.routers.giteaWeb-rtr.service=giteaWeb-svc
      - traefik.http.services.giteaWeb-svc.loadbalancer.server.port=3000
      # ssh
      - traefik.tcp.routers.giteaSSH-rtr.entrypoints=ssh
      - traefik.tcp.routers.giteaSSH-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.giteaSSH-rtr.service=giteaSSH-svc
      - traefik.tcp.services.giteaSSH-svc.loadbalancer.server.port=22

  gitea-db:
    image: postgres:${GITEA_DB_VERSION:-14-alpine}
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    secrets: [ GITEA_DB_PASS ]
    environment:
      POSTGRES_DB: "${GITEA_DB_NAME:-giteadb}"
      POSTGRES_USER: "${GITEA_DB_USER:-gitea}"
      POSTGRES_PASSWORD: /run/secrets/GITEA_DB_PASS
    volumes:
      - "${SPRING_VOLUME}/gitea/db:/var/lib/postgresql/data"
    labels:
      - traefik.enable=false
    healthcheck:
      test: pg_isready -U "${GITEA_DB_USER:-gitea}" -d "${GITEA_DB_NAME:-giteadb}"
      interval: 10s
      timeout: 2s
      retries: 10

networks:
  gitea:
    name: gitea
  proxy:
    external: true
    name: proxy
  smtp:
    external: true
    name: smtp
