http:
  routers:
    oberon:
      entryPoints:
        - websecure
      rule: "Host(`whoami.{{ domain }}`) || Host(`media.{{ domain }}`) || Host(`torrent.{{ domain }}`)"
      service: oberon-service

  services:
    # Service to check oberon server is up
    oberon-service:
      loadBalancer:
        servers:
          - url: https://traefik2.{{ domain }}
