http:
  routers:
    oberon:
      entryPoints:
        - websecure
      rule: "Host(`whoami.{{ domain }}`) || Host(`media.{{ domain }}`) || Host(`photos.{{ domain }}`)"
      service: oberon-service

    oberon-auth:
      entryPoints:
        - websecure
      rule: "Host(`torrent.{{ domain }}`)"
      service: oberon-service
      middlewares:
        - authelia@docker

  services:
    # Service to check oberon server is up
    oberon-service:
      loadBalancer:
        servers:
          - url: https://traefik-int.{{ domain }}
