tls:
  options:
    default:
      # Set minimum supported TLS version to TLS 1.2
      minVersion: VersionTLS12
      cipherSuites:
        # Recommended cipher suites for TLS 1.2
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        # Recommended cipher suites for TLS 1.3
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305

    tlsv13only:
      # Enforce minimum TLS version as 1.3 (for environments that require higher security)
      minVersion: VersionTLS13
