---
- name: Config adguard service
  hosts: calisto
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
  tasks:
    - name: Create adguard config directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: homelab
      loop:
        - adguard
        - adguard/config
        - adguard/data
