---
- name: Config adguard service
  hosts: adguard
  vars:
    path: "{{ lookup('env', 'VOLPATH') }}"
  tasks:
    - name: Make directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - adguard
        - adguard/config
        - adguard/data
      become: true
      become_user: root
