---
- name: Config authelia service
  hosts: calisto
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
    domain: "{{ lookup('env', 'DOMAIN') }}"
    smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
    smtp_host: "{{ lookup('env', 'SMTP_HOST') }}"
    smtp_port: "{{ lookup('env', 'SMTP_PORT') }}"
    smtp_sender: "{{ lookup('env', 'SMTP_SENDER') }}"
    jellyfin_client_id: "{{ lookup('env', 'JELLYFIN_CLIENT_ID') }}"
    jellyfin_client_secret: "{{ lookup('env', 'JELLYFIN_CLIENT_SECRET') }}"
    immich_client_id: "{{ lookup('env', 'IMMICH_CLIENT_ID') }}"
    immich_client_secret: "{{ lookup('env', 'IMMICH_CLIENT_SECRET') }}"
    # oidc_jwks_key: "{{ lookup('env', 'AUTHELIA_OIDC_JWKS_KEY') | b64decode }}"
  tasks:
    - name: Create authelia config directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: homelab
      loop:
        - authelia
        - authelia/config
        - authelia/data

    - name: Copy authelia config files
      ansible.builtin.template:
        src: "../services/authelia/{{ item }}"
        dest: "{{ path }}/authelia/config/{{ item }}"
        mode: '0644'
        owner: homelab
        group: homelab
      loop:
        - configuration.yml
        - users_database.yml
