---
- name: Configure homelab user and set permissions for /mnt/user/appdata/homelab
  hosts: calisto
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
  tasks:
    - name: Create the 'homelab' user
      ansible.builtin.user:
        name: homelab
        uid: 1003
        home: /nonexistent
        create_home: false
        shell: /sbin/nologin  # Assign a valid shell
        state: present

    - name: Ensure the 'docker' group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add the 'homelab' user to the 'docker' group
      ansible.builtin.user:
        name: homelab
        groups: docker
        append: true

    - name: Set permissions for intermediate directories to 755
      ansible.builtin.file:
        path: "{{ path | dirname }}"
        mode: '0755'
        state: directory
        owner: root
        group: root

    - name: Set ownership of /mnt/user/appdata/homelab to 'homelab'
      ansible.builtin.file:
        path: "{{ path }}"
        mode: '0700'
        owner: homelab
        group: homelab
        state: directory
