---
- name: Configure homelab user and set permissions for /mnt/user/appdata/homelab
  hosts: homelab
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
  tasks:
    # - name: Create the 'homelab' user
    #   ansible.builtin.user:
    #     name: homelab
    #     uid: 1003
    #     home: /nonexistent
    #     create_home: false
    #     shell: /sbin/nologin  # Assign a valid shell
    #     state: present
    #   when: inventory_hostname == 'calisto'

    # - name: Ensure the 'docker' group exists
    #   ansible.builtin.group:
    #     name: docker
    #     state: present
    #   when: inventory_hostname == 'calisto'

    # - name: Add the 'homelab' user to the 'docker' group
    #   ansible.builtin.user:
    #     name: homelab
    #     groups: docker
    #     append: true
    #   when: inventory_hostname == 'calisto'

    # - name: Set permissions for intermediate directories to 755
    #   ansible.builtin.file:
    #     path: "{{ item }}"
    #     mode: '0755'
    #     state: directory
    #     owner: root
    #     group: root
    #   with_items:
    #     - /mnt
    #     - /mnt/user
    #     - /mnt/user/appdata
    #   when: inventory_hostname == 'calisto'

    # - name: Set ownership of /mnt/user/appdata/homelab to 'homelab'
    #   ansible.builtin.file:
    #     path: "{{ path }}"
    #     mode: '0700'
    #     owner: homelab
    #     group: homelab
    #     recurse: true
    #     state: directory
    #   when: inventory_hostname == 'calisto'

    # - name: Set ownership of /mnt/user/appdata/homelab to 'homelab'
    #   ansible.builtin.file:
    #     path: "{{ path }}"
    #     mode: '0700'
    #     owner: homelab
    #     group: users
    #     recurse: true
    #     state: directory
    #   when: inventory_hostname == 'oberon'
