---
# Playbook to install Docker and Docker Compose on Raspberry Pi OS
# References:
# https://docs.docker.com/engine/install/debian/
# https://docs.docker.com/engine/install/linux-postinstall/
- name: Install Docker and Docker Compose on Raspberry Pi OS
  hosts: calisto
  become: true
  vars:
    target_user: vekio  # Define the user to add to the docker group

  tasks:
    # Update and upgrade all packages to the latest version
    - name: Upgrade all system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    # Install necessary packages for Docker installation
    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    # Ensure the directory for apt keyrings exists to store Docker's GPG key
    - name: Ensure apt keyring directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    # Check if the Docker GPG key already exists
    - name: Check Docker GPG key presence
      ansible.builtin.stat:
        path: /etc/apt/keyrings/docker.asc
      register: docker_gpg

    # Download the Docker GPG key if it doesn't exist
    - name: Download Docker GPG key if not present
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 'a+r'
      when: not docker_gpg.stat.exists

    # Add Docker's repository to the sources list
    - name: Add Docker repository to sources list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: >
          deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        create: true
        state: present
        backup: true
        mode: '0644'

    # Update apt cache after adding the new Docker repository
    - name: Update apt cache following repository addition
      ansible.builtin.apt:
        update_cache: true

    # Install Docker components
    - name: Install Docker Engine, CLI, and plugins
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    # Ensure the Docker group exists on the system
    - name: Ensure Docker group is present
      ansible.builtin.group:
        name: docker
        state: present

    # Add specified user to the Docker group
    - name: Add specified user to Docker group
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: docker
        append: true

    # Reboot the machine to apply changes, if necessary
    - name: Reboot the machine if required
      ansible.builtin.reboot:
        msg: "Rebooting to apply Docker configuration changes"
