---
- name: Config jellyfin service
  hosts: oberon
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
    media_path: "{{ lookup('env', 'MEDIA_PATH') }}"
  tasks:
    - name: Create jellyfin config directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: users
      loop:
        - jellyfin
        - jellyfin/cache
        - jellyfin/config

    - name: Create media directories for movies and tvshows
      ansible.builtin.file:
        path: "{{ media_path }}/{{ item }}"
        state: directory
        mode: '0770'
        owner: homelab
        group: users
        recurse: true
      loop:
        - movies
        - tvshows
