---
- name: Config jellyfin service
  hosts: jellyfin
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
  tasks:
    - name: Make directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - jellyfin
        - jellyfin/cache
        - jellyfin/config
      become: true
      become_user: root
