---
- name: Config qbittorrent service
  hosts: oberon
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
    download_path: "{{ lookup('env', 'DOWNLOAD_PATH') }}"
  tasks:
    - name: Create qbittorrent config directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: users
      loop:
        - qbittorrent
        - qbittorrent/config

    - name: Create directories for qbittorrent downloads
      ansible.builtin.file:
        path: "{{ download_path }}/{{ item }}"
        state: directory
        mode: '0770'
        owner: homelab
        group: users
        recurse: true
      loop:
        - qbittorrent
        - qbittorrent/watch
        - qbittorrent/complete
        - qbittorrent/incomplete
        - qbittorrent/torrents
