---
- name: Create secrets files
  hosts: calisto
  become: true
  vars:
    path: "{{ lookup('env', 'VOL_PATH') }}"
    jwt_secret: "{{ lookup('env', 'AUTHELIA_JWT_SECRET') }}"
    session_secret: "{{ lookup('env', 'AUTHELIA_SESSION_SECRET') }}"
    storage_encryption_key: "{{ lookup('env', 'AUTHELIA_STORAGE_ENCRYPTION_KEY') }}"
    oidc_hmac_secret: "{{ lookup('env', 'AUTHELIA_OIDC_HMAC_SECRET') }}"
    smtp_token: "{{ lookup('env', 'SMTP_TOKEN') }}"
    authelia_secrets:
      - name: JWT_SECRET
        content: "{{ jwt_secret }}"
      - name: SESSION_SECRET
        content: "{{ session_secret }}"
      - name: STORAGE_ENCRYPTION_KEY
        content: "{{ storage_encryption_key }}"
      - name: OIDC_HMAC_SECRET
        content: "{{ oidc_hmac_secret }}"
    smtp_secrets:
      - name: SMTP_PASSWORD
        content: "{{ smtp_token }}"
  tasks:
    - name: Make directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: homelab
      loop:
        - authelia/secrets
        - authelia/config/oidc/jwks
        - smtp/secrets


    - name: Create authelia secrets files
      ansible.builtin.copy:
        dest: "{{ path }}/authelia/secrets/{{ item.name }}"
        content: "{{ item.content }}"
        mode: '0600'
        owner: homelab
        group: homelab
      loop: "{{ authelia_secrets }}"


    - name: Create smtp secret files
      ansible.builtin.copy:
        dest: "{{ path }}/smtp/secrets/{{ item.name }}"
        content: "{{ item.content }}"
        mode: '0600'
        owner: homelab
        group: homelab
      loop: "{{ smtp_secrets }}"


    # - name: Decode JWKS key
    #   ansible.builtin.copy:
    #     content: "{{ oidc_jwks_key | b64decode }}"
    #     dest: "{{ path }}/authelia/config/oidc/jwks/rsa.2048.key"
    #     mode: '0600'
    #   become: true
    #   become_user: root
