---
- name: Create secrets files
  hosts: localhost
  vars:
    jwt_secret: "{{ lookup('env', 'AUTHELIA_JWT_SECRET') }}"
    session_secret: "{{ lookup('env', 'AUTHELIA_SESSION_SECRET') }}"
    storage_encryption_key: "{{ lookup('env', 'AUTHELIA_STORAGE_ENCRYPTION_KEY') }}"
    oidc_hmac_secret: "{{ lookup('env', 'AUTHELIA_OIDC_HMAC_SECRET') }}"
    smtp_token: "{{ lookup('env', 'SMTP_TOKEN') }}"
    authelia_secrets:
      - name: JWT_SECRET
        content: "{{ jwt_secret }}"
      - name: SESSION_SECRET
        content: "{{ session_secret }}"
      - name: STORAGE_ENCRYPTION_KEY
        content: "{{ storage_encryption_key }}"
      - name: OIDC_HMAC_SECRET
        content: "{{ oidc_hmac_secret }}"
    smtp_secrets:
      - name: SMTP_PASSWORD
        content: "{{ smtp_token }}"
  tasks:
    - name: Make directories
      ansible.builtin.file:
        path: "../services/{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - authelia/secrets
        - smtp/secrets

    - name: Create authelia secrets files
      ansible.builtin.copy:
        dest: "../services/authelia/secrets/{{ item.name }}"
        content: "{{ item.content }}"
        mode: '0600'
      loop: "{{ authelia_secrets }}"

    - name: Create smtp secret files
      ansible.builtin.copy:
        dest: "../services/smtp/secrets/{{ item.name }}"
        content: "{{ item.content }}"
        mode: '0600'
      loop: "{{ smtp_secrets }}"
