---
- name: Config status service
  hosts: calisto
  become: true
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    path: "{{ lookup('env', 'VOL_PATH') }}"
  tasks:
    - name: Create status config directories
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0700'
        owner: homelab
        group: homelab
      loop:
        - status
        - status/config

    - name: Create status html directory
      ansible.builtin.file:
        path: "{{ path }}/{{ item }}"
        state: directory
        mode: '0755'
        owner: homelab
        group: homelab
      loop:
        - status/html

    - name: Copy status html files
      ansible.builtin.copy:
        src: "../services/status/html/{{ item }}"
        dest: "{{ path }}/status/html/{{ item }}"
        mode: '0644'
        owner: homelab
        group: homelab
      loop:
        - index.html
        - 404.html
        - unregistered.html

    - name: Copy status config files
      ansible.builtin.template:
        src: "../services/status/config/{{ item }}"
        dest: "{{ path }}/status/config/{{ item }}"
        mode: '0644'
        owner: homelab
        group: homelab
      loop:
        - nginx.conf
