---
- name: Config traefik service
  hosts: localhost
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    acme_cert_email: "{{ lookup('env', 'ACME_CERT_EMAIL') }}"
    acme_letsencrypt_url: "{{ lookup('env', 'ACME_LETSENCRYPT_URL') }}"
    oberon_path: "{{ lookup('env', 'OBERON_PATH') }}"
  tasks:
    - name: Make directories
      ansible.builtin.file:
        path: "{{ oberon_path }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - traefik
        - traefik/cetificates
        - traefik/config/dynamic

    - name: Copy files
      ansible.builtin.template:
        src: "../traefik/config/{{ item }}"
        dest: "{{ oberon_path }}/traefik/config/{{ item }}"
        mode: '0644'
      loop:
        - traefik.yml
