---
- name: Configuración en localhost
  hosts: localhost
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    acme_cert_email: "{{ lookup('env', 'ACME_CERT_EMAIL') }}"
    acme_letsencrypt_url: "{{ lookup('env', 'ACME_LETSENCRYPT_URL') }}"
    oberon_path: "{{ lookup('env', 'OBERON_PATH') }}"
  tasks:
    # - name: Verificar variables de entorno
    #   ansible.builtin.debug:
    #     msg: "DOMAIN={{ domain }}, ACME_CERT_EMAIL={{ acme_cert_email }}, ACME_LETSENCRYPT_URL={{ acme_letsencrypt_url }}, OBERON_PATH={{ oberon_path }}"

    - name: Crear directorios necesarios
      ansible.builtin.file:
        path: "/home/vekio/.config/homelab/volume/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - traefik
        - traefik/cetificates
        - traefik/config/dynamic

    - name: Copiar archivos y reemplazar placeholders
      ansible.builtin.template:
        src: "/home/vekio/source/homelab/traefik/config/{{ item }}"
        dest: "/home/vekio/.config/homelab/volume/traefik/config/{{ item }}"
        mode: '0644'
      loop:
        - traefik.yml
