---
- name: Create qBittorrent config directory
  ansible.builtin.file:
    path: "{{ qbittorrent_path }}/config"
    state: directory
    mode: '0700'
    owner: homelab
    group: users

- name: Create qBittorrent download directory
  ansible.builtin.file:
    path: "{{ qbittorrent_download_path }}"
    state: directory
    mode: '0755'
    owner: homelab
    group: users

- name: Create qBittorrent download subdirectories
  ansible.builtin.file:
    path: "{{ qbittorrent_download_path }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: homelab
    group: users
    recurse: true
  loop:
    - watch
    - complete
    - incomplete
    - torrents
